# Generated by Django 2.0 on 2018-01-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paperauthor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('ACC', 'Accepted'), ('AMI', 'Accepted with minor correction'), ('AMA', 'Accepted with major correction'), ('REJ', 'Rejected')], default=None, max_length=3, null=True)),
                ('comments_to_author', models.TextField(blank=True, default=None, null=True)),
                ('comments_to_editor', models.TextField(blank=True, default=None, null=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paperauthor.Paper')),
            ],
        ),
    ]
