# Generated by Django 2.0.1 on 2018-01-29 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0002_auto_20180129_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paperreviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACC', 'Accept'), ('REJ', 'Reject')], default=None, max_length=3, null=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paperauthor.Paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
