# Generated by Django 2.0.1 on 2018-02-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperreviewer', '0002_paperreviewrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperreviewrequest',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperauthor.Paper'),
        ),
    ]
