# Generated by Django 2.0.2 on 2018-02-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperreviewer', '0003_auto_20180201_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperreviewrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('ACC', 'Accept'), ('REJ', 'Reject')], default=None, max_length=3, null=True),
        ),
    ]
