# Generated by Django 2.0.2 on 2018-02-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperreviewer', '0004_auto_20180218_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperreview',
            name='final_comments_to_author',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
