# Generated by Django 2.0.2 on 2018-02-18 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperreviewer', '0005_paperreview_final_comments_to_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperreviewrequest',
            name='paper',
            field=models.ForeignKey(limit_choices_to={'reviewer': None}, on_delete=django.db.models.deletion.CASCADE, to='paperauthor.Paper'),
        ),
        migrations.AlterField(
            model_name='paperreviewrequest',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
