# Generated by Django 2.0 on 2018-01-24 16:00

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import slugger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/workspace/eclipse/ejournal/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('slug', slugger.fields.AutoSlugField(populate_from='title', unique=True)),
                ('author', models.ForeignKey(limit_choices_to={'groups__name': 'author'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperauthor.Category')),
                ('keywords', models.ManyToManyField(blank=True, to='paperauthor.Keyword')),
                ('reviewer', models.ForeignKey(blank=True, default=None, limit_choices_to={'groups__name': 'reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewpaper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='reviewer_emails',
            field=models.ManyToManyField(blank=True, to='paperauthor.ReviewerEmail'),
        ),
    ]
