# Generated by Django 2.0.1 on 2018-01-29 14:56

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/workspace/python/django/ejournal/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
