# Generated by Django 2.0.1 on 2018-02-01 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0002_auto_20180129_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='track_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
