# Generated by Django 2.0.2 on 2018-02-18 07:10

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0003_paper_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='description',
            new_name='abstract',
        ),
        migrations.AlterField(
            model_name='paper',
            name='upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/workspace/python/django/ejournal2/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
