# Generated by Django 2.0.2 on 2018-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0004_auto_20180218_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
