# Generated by Django 2.0.2 on 2018-02-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0005_paper_is_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='is_reviewed',
            new_name='review_complete',
        ),
    ]
