# Generated by Django 2.0.2 on 2018-02-18 10:51

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0006_auto_20180218_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperResubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_corrections', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/workspace/python/django/ejournal2/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('original_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmissions_set', to='paperauthor.Paper')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paperauthor.Paper')),
            ],
        ),
    ]
