# Generated by Django 2.0.2 on 2018-02-18 10:52

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0007_paperresubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperresubmission',
            name='performed_corrections',
            field=models.FileField(default=0, storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/workspace/python/django/ejournal2/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
    ]
