# Generated by Django 2.0.2 on 2018-02-18 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0008_paperresubmission_performed_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='submission_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
