# Generated by Django 2.0.2 on 2018-09-30 07:40

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperauthor', '0010_auto_20180612_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperFinalSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['docx'])])),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/project/ejournal/ejm/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='paperresubmission',
            name='performed_corrections',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/project/ejournal/ejm/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='paperresubmission',
            name='suggested_corrections',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/amardhruva/project/ejournal/ejm/protected'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='paperfinalsubmission',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paperauthor.Paper'),
        ),
    ]
