# Generated by Django 2.0 on 2018-01-17 17:34

from django.db import migrations
from django.contrib.auth.models import Group

def add_groups(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    groups=('author', 'reviewer', 'editor')
    for x in groups:
        my_group, created = Group.objects.get_or_create(name=x)

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]
