# Generated by Django 2.0.2 on 2018-02-02 16:20

import django.core.validators
from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('upload', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('preview_image', models.ImageField(upload_to='')),
                ('slug', slugger.fields.AutoSlugField(populate_from='name', unique=True)),
            ],
        ),
    ]
