# Generated by Django 2.0.2 on 2018-02-18 07:10

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baseportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedjournal',
            name='slug',
            field=slugger.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
