# Generated by Django 2.0.2 on 2018-03-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseportal', '0002_auto_20180218_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='publishedjournal',
            name='published_date',
        ),
        migrations.AddField(
            model_name='publishedjournal',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseportal.Volume'),
        ),
    ]
